### ISSUE TITLE
좋아요 엔티티 단위 기능 테스트

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#10]
# Description
좋아요 엔티티 단위 기능 테스트

# Todo
- [x] 좋아요 클릭 or 취소시 회원, 숙소 정보 업데이트 되는지 테스트
- [x] 좋아요 클릭 or 취소시 회원성향 가중치 업데이트 되는지 테스트
- [x] 좋아요 클릭 or 취소시 회원 대표 태그 업데이트 되는지 테스트

# ETC
