### ISSUE TITLE
회원성향 엔티티 단위 기능 테스트

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#11]
# Description
회원성향 엔티티 단위 기능 테스트

# Todo
- [x] 가중치 엔티티에서 태그가 제대로 구해지는지 테스트
- [x] 회원 숙소 가중치합 제대로 구해지는지 테스트
- [x] 회원성향에 따른 태그가 제대로 구해지는지 테스트

# ETC
