### ISSUE TITLE
DB를 기존에 연결된 H2에서 Mysql로 변경

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#12]
# Description
DB를 기존에 연결된 H2에서 Mysql로 변경

# Todo
- [x] H2연결 해제 후 Mysql연동
- [x] 테스트 DB생성 및 작동
- [x] 숙소정보들 Mysql로 옮기기

# ETC
