### ISSUE TITLE
좋아요 API 개발

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#14]
# Description
좋아요 API 개발

# Todo
- [x] 유저, 숙소에 대한 좋아요 정보 받는 기능 추가
- [x] 유저, 숙소에 대한 좋아요 정보 받는 테스트 추가
- [x] 좋아요 클릭시 추가 and 취소 api

# ETC
- [x] Api 테스트용 샘플 데이터 추가
