### ISSUE TITLE
회원 도메인 개발

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#6]
# Description
회원 도메인 개발

# Todo
- [x] 회원 리포지토리 개발
- [x] 회원 서비스 개발
- [x] 회원 기능 테스트

# ETC
회원 성향 클래스 틀 만들어놓기
