### ISSUE TITLE
좋아요 도메인 개발

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#8]
# Description
좋아요 도메인 개발

# Todo
- [x] 좋아요 엔티티에 비즈니스 로직 추가
- [x] 좋아요 리포지토리 개발
- [x] 좋아요 서비스 개발
- [x] 좋아요 기능, 취소 기능 테스트

# ETC
