### ISSUE TITLE
회원성향 도메인 개발

### ISSUE THREAD

**Issue by WonSubSub** [ywoo12321/Accommodation-Refactoring#9]
# Description
회원성향 도메인 개발

# Todo
- [x] 회원성향 엔티티 수정
- [x] 회원성향 리포지토리 개발
- [x] 회원성향 서비스 개발
- [x] 회원성향 기능 테스트(좋아요눌렀을시, 취소할시, 평소)

# ETC
좋아요 서비스도 수정
